{% set version = "0.5.1" %}

package:
  name: composeml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/composeml/composeml-{{ version }}.tar.gz
  sha256: 4656dcdca06f6877e9f50d6a08a62fc628d7f643b37e85d67068643be5610be0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pandas >=0.23.0
    - numpy >=1.13.3
    - tqdm >=4.19.2
    - matplotlib >=3.0.2
    - seaborn >=0.9.0

test:
  commands:
    - pytest --pyargs composeml
  imports:
    - composeml
  requires:
    - pytest ==4.4.1
    - fastparquet >=0.1.6
    - packaging ==20.4
    - featuretools >=0.9.0
  source_files:
    - composeml/*

about:
  doc_url: https://compose.featurelabs.com
  dev_url: https://github.com/FeatureLabs/compose
  home: https://compose.featurelabs.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library for automated prediction engineering.

extra:
  recipe-maintainers:
    - jeff-hernandez
