{% set version = "0.8.0" %}

package:
  name: composeml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/composeml/composeml-{{ version }}.tar.gz
  sha256: 88122867dc377c1b802ce360cecbc64add2da6bf31aec7f51b52728ff371aadd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.7
    - pandas >=1.1.0
    - tqdm >=4.32.0
    - matplotlib >=3.3.3
    - seaborn >=0.11.0

test:
  commands:
    - pytest --pyargs composeml
  imports:
    - composeml
  requires:
    - pytest ==6.0.1
    - fastparquet ==0.5.0
    - featuretools >=1.4.0
    - evalml ==0.41.0
  source_files:
    - composeml/*

about:
  doc_url: https://compose.featurelabs.com
  dev_url: https://github.com/FeatureLabs/compose
  home: https://compose.featurelabs.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library for automated prediction engineering.

extra:
  recipe-maintainers:
    - gsheni
    - jeff-hernandez
    - rwedge
    - tamargrey
    - thehomebrewnerd
