{% set version = "0.10.1" %}

package:
  name: composeml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/composeml/composeml-{{ version }}.tar.gz
  sha256: d87fc181be72fadec16ea0e44ebd363b4e2e3620c87c8b2cae6e236fd00761d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8.*
  run:
    - matplotlib >=3.3.3
    - pandas >=1.3.0
    - python >=3.8.*
    - seaborn >=0.11.0
    - tqdm >=4.32.0
test:
  commands:
    - pytest --pyargs composeml
  imports:
    - composeml
  requires:
    - featuretools >=1.4.0
    - pip >=21.3.1
    - pyarrow >=3.0.0
    - pytest-cov ==3.0.0
    - pytest-xdist >=2.5.0
    - wheel >=0.33.1
    - woodwork >=0.11.0
  source_files:
    - composeml/*

about:
  doc_url: https://compose.alteryx.com
  dev_url: https://github.com/alteryx/compose
  home: https://compose.alteryx.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library for automated prediction engineering.

extra:
  recipe-maintainers:
    - gsheni
    - jeff-hernandez
    - rwedge
    - tamargrey
    - thehomebrewnerd
    - dvreed77
